name: self-driving-lab-demo
channels:
  - defaults
  - conda-forge
  # - pytorch
  # - nvidia
  # - fastai
dependencies:
  - python>=3.6,<3.12
  - pip
  # BASICS
  - numpy
  - scipy
  - pandas
  - tqdm
  - click
  - ipython
  # VISUALIZATION
  - matplotlib
  # - ipympl  # interactive matplotlib plots
  # - seaborn
  # - altair
  # - yellowbrick
  # ML, STATS & DEEP LEARNING
  # - statsmodels
  # - scikit-learn
  # - sktime
  # - tslearn
  # - xgboost
  # - catboost
  # - lightgbm
  # - pytorch
  # - pytorch-cuda=11.8
  # - fastai  # activate fastai channel above!
  # - tensorflow
  # - keras
  # - spacy
  # OTHER TOOLS
  # - optuna
  # - dask
  # - snakeviz
  - pip:
     - -e .  # install git checkout of self-driving-lab-demo in editable mode
     # add here only pip-packages that are not available in conda/conda-forge! E.g.:
     # - blinkt
     # - adafruit-circuitpython-as7341
     - ax-platform < 1
     - acrylic
     # - icecream
     # - jax
     # - numpyro
     # - funsor
     # - neptune-client
     # - neptune-contrib

  # DEVELOPMENT ONLY PACKAGES (could also be kept in a separate environment file)
  # - jupyterlab
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  # - nbdime
  # - nbstripout
  - sphinx
  # - recommonmark
  # - pandoc
