"""WiFi and Adafruit IO Login Info. Rename to secrets.py"""
SSID = "Enter your SSID here"
PASSWORD = "Enter your WiFi password here"
ADAFRUIT_IO_USERNAME = "Your account name at io.adafruit.com"
ADAFRUIT_IO_KEY = "Your API key from io.adafruit.com"
