"""WiFi Login Info. Rename this file to secrets.py"""
SSID = "Enter your SSID here"
PASSWORD = "Enter your WiFi password here"
MONGODB_API_KEY = "Enter your Mongo DB API Key (optional)"
MONGODB_COLLECTION_NAME = "Enter the name of the Mongo DB collection (optional)"
DEVICE_NICKNAME = "For MongoDB, enter whatever name you want here (optional)"
